language: scala

jdk:
  - openjdk8

scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_1e3c8fda68a9_key -iv $encrypted_1e3c8fda68a9_iv
      -in secring.gpg.enc -out secring.gpg -d;
    fi
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install ruby_dep -v 1.3.1
  - gem install jekyll -v 3.4.3
  - gem install jekyll-redirect-from
  - nvm install 6
  - nvm use 6
  - node --version

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage "testOnly * -- -minSuccessfulTests 100000" coverageAggregate coverageReport

stages:
  - test
  - validation
  - deploy

jobs:
  include:
    - stage: validation
      script:
        - sbt ++$TRAVIS_SCALA_VERSION orgValidateFiles
        - sbt ++$TRAVIS_SCALA_VERSION orgCheckSettings
        - sbt ++$TRAVIS_SCALA_VERSION docs/tut
        - bash <(curl -s https://codecov.io/bash)
      scala: 2.13.1
    - stage: deploy
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
            if grep -q "SNAPSHOT" version.sbt; then
              sbt ++$TRAVIS_SCALA_VERSION publish;
            else
              sbt orgUpdateDocFiles;
              git reset --hard HEAD;
              git clean -f;
              git checkout master;
              git pull origin master;
              sbt release;
              sbt docs/publishMicrosite;
            fi
          fi
      scala: 2.13.1

cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.coursier/cache -name "*.lock" -type f -delete
