language: scala
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_1e3c8fda68a9_key -iv $encrypted_1e3c8fda68a9_iv
    -in secring.gpg.enc -out secring.gpg -d;
  fi
script:
  - sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
after_success:
  - bash <(curl -s https://codecov.io/bash) -t d8c6d7cf-f05c-4953-9f6e-ff046716a0f0
  - sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess